config/routes.rb
Rails.application.routes.draw do
  resources :students

  root to: 'visitors#index'
  devise_for :users
  resources :users

  post 'students/new' => 'students#new'
  
 end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:classroom]
      @students = Student.where(:classroom => params[:classroom])
    else
      @students = Student.all.order(:last_name)
    end
    #respond_with(@students)
    create_email_string(@students)
   
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end
  
  def create_email_string(string)
     @string = string.collect(&:email1).join(';')
     @string2 = @string + ";" + string.collect(&:email2).join(';')
  end
   
  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :parent1, :parent2, :email1, :email2, :email3, :email4, :classroom)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

  <li><%= link_to 'Add Child', new_student_path %></li>
  <li><%= link_to 'All Children', students_path %></li>
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Classes <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Movers', students_path(classroom: 'Movers')  %></li>
      <li><%= link_to 'Wigglers', students_path(classroom: 'Wigglers')  %></li>
      <li><%= link_to 'Shakers', students_path(classroom: 'Shakers')  %></li>
      <li class="divider"></li>
      <li><%= link_to 'Experimenters', students_path(classroom: 'Experimenters')  %></li>
      <li><%= link_to 'Creators', students_path(classroom: 'Creators')  %></li>
      <li><%= link_to 'Investigators', students_path(classroom: 'Investigators')  %></li>
      <li class="divider"></li>
      <li><%= link_to 'Dreamers', students_path(classroom: 'Dreamers')  %></li>
      <li><%= link_to 'Inventors', students_path(classroom: 'Inventors')  %></li>
      <li class="divider"></li>
      <li><%= link_to 'Explorers', students_path(classroom: 'Explorers')  %></li>
      <li><%= link_to 'K/D', students_path(classroom: 'K/D')  %></li>
    </ul>
 </li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SRCC Emails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "SRCC Emails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
		<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
		<!-- Latest compiled and minified JavaScript -->
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :parent1 %><br>
    <%= f.text_field :parent1 %>
  </div>
  <div class="field">
    <%= f.label :parent2 %><br>
    <%= f.text_field :parent2 %>
  </div>
  <div class="field">
    <%= f.label :email1 %><br>
    <%= f.text_field :email1 %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br>
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :email3 %><br>
    <%= f.text_field :email3 %>
  </div>
  <div class="field">
    <%= f.label :email4 %><br>
    <%= f.text_field :email4 %>
  </div>
   <div class="field">
  <%= f.select :classroom, [['Creators','Creators'],['Dreamers','Dreamers'],['Experimenters','Experimenters'],['Explorers','Explorers'],['Inventors','Inventors'],['Investigators','Investigators'],['K/D','K/D'],['Movers','Movers'],['Shakers','Shakers'],['Wigglers','Wigglers']] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/creators.html.erb
<p id="notice"><%= notice %></p>

<h1>Movers</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/dreamers.html.erb
<p id="notice"><%= notice %></p>

<h1>Dreamers</h1>
<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>

<br>
<br>

app/views/students/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/experimenters.html.erb
<p id="notice"><%= notice %></p>

<h1>Experimenters</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/explorers.html.erb
<p id="notice"><%= notice %></p>

<h1>Explorers</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<% if params[:classroom] %>
<h1><%= params[:classroom]%></h1>
<% else %>
<h1>All SRCC Children</h1>
<% end %>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent 1</th>
      <th>Parent 2</th>
      <th>Email 1</th>
      <th>Email 2</th>
      <th>Email 3</th>
      <th>Email 4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.last_name %>, <%= student.first_name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>

<br>
<br>

app/views/students/inverntors.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventors</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/investigators.html.erb
<p id="notice"><%= notice %></p>

<h1>Investigators</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/kds.html.erb
<p id="notice"><%= notice %></p>

<h1>K/D</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/movers.html.erb
<p id="notice"><%= notice %></p>

<h1>Movers</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/shakers.html.erb
<p id="notice"><%= notice %></p>

<h1>Movers</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.first_name %> <%= @student.last_name %>
</p>

<p>
  <strong>Parent1:</strong>
  <%= @student.parent1 %>
</p>

<p>
  <strong>Parent2:</strong>
  <%= @student.parent2 %>
</p>

<p>
  <strong>Email1:</strong>
  <%= @student.email1 %>
</p>

<p>
  <strong>Email2:</strong>
  <%= @student.email2 %>
</p>

<p>
  <strong>Email3:</strong>
  <%= @student.email3 %>
</p>

<p>
  <strong>Email4:</strong>
  <%= @student.email4 %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @student.classroom %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/students/wigglers.html.erb
<p id="notice"><%= notice %></p>

<h1>Wigglers</h1>

<div class="row">
  <div class="col-md-6">
   <table class="table">       
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent1</th>
      <th>Parent2</th>
      <th>Email1</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Email4</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.parent1 %></td>
        <td><%= student.parent2 %></td>
        <td><%= student.email1 %></td>
        <td><%= student.email2 %></td>
        <td><%= student.email3 %></td>
        <td><%= student.email4 %></td>
        <td><%= student.classroom %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>


<br>
<%= button_to('Send Email', 'mailto:' + @string2, class: "btn btn-primary")%>
<br>
<br>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<br/><br/>
<img src="assets/srcc.jpg">